spring:
  datasource:
#    url: jdbc:mariadb://bbangsco.co.kr:3306/gun5032
#    username: gun5032
#    password: see010811!!
#    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/bbangs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true
  resources.static-locations: file:src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: gun235448@gmail.com
    password: kcmdwbmguaqrftii
    port: '587'

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

file:
  upload:
    mainImg: /Users/wangsungtaek/images
    collaboImg: /Users/wangsungtaek/images/collaboImg
    coverImg: /Users/wangsungtaek/images/coverImg