spring:
  datasource:
    url: jdbc:mariadb://bbangsco.co.kr:3306/gun5032
    username: gun5032
    password: see010811!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: gun235448@gmail.com
    password: kcmdwbmguaqrftii
    port: '587'

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

